" Indentation 
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Syntax
syntax on
filetype plugin indent on
set showmatch
set hlsearch
set incsearch

" Line numbers
set number
set relativenumber
